version: '3.8'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: pablo
      POSTGRES_PASSWORD: pablopassword
      POSTGRES_DB: nodepg
    ports:
      - 5432:5432
